"""Minimal finite groups for the QT group lift.

The lift of Eq. (S47)-(S48) only needs a Cayley table and inverses: the
left-regular action ``[lambda_a]_{g,h} = delta_{h, a^{-1} g}`` and the
right-regular action ``[rho_b]_{h,g} = delta_{h, gb}``. Element ``0`` is always
the identity.
"""
from __future__ import annotations

import numpy as np

__all__ = ["Group"]


class Group:
    """A finite group as a Cayley table with the identity at index 0."""

    def __init__(self, mult, name: str = ""):
        self.mult = np.asarray(mult, dtype=int)
        self.L = int(self.mult.shape[0])
        self.name = name
        idn = np.arange(self.L)
        if not (np.array_equal(self.mult[0], idn) and np.array_equal(self.mult[:, 0], idn)):
            raise ValueError("element 0 must be the identity")
        self.inv = np.array([int(np.flatnonzero(self.mult[a] == 0)[0])
                             for a in range(self.L)], dtype=int)

    def __len__(self) -> int:
        return self.L

    def __repr__(self) -> str:
        return f"Group({self.name or '?'}, |G|={self.L})"

    # -- constructors ----------------------------------------------------
    @classmethod
    def cyclic(cls, L: int) -> "Group":
        """``C_L`` -- elements are residues, identity 0."""
        a = np.arange(L)
        return cls((a[:, None] + a[None, :]) % L, f"C{L}")

    @classmethod
    def dihedral(cls, m: int) -> "Group":
        """``D_m`` of order ``2m``; element ``r^i s^e`` sits at index ``2i + e``."""
        L = 2 * m
        mult = np.empty((L, L), dtype=int)
        for x in range(L):
            i, e = divmod(x, 2)
            for y in range(L):
                j, f = divmod(y, 2)
                k = (i + j if e == 0 else i - j) % m       # s r^j s^-1 = r^-j
                mult[x, y] = 2 * k + (e ^ f)
        return cls(mult, f"D{m}")

    @classmethod
    def from_perms(cls, gens) -> "Group":
        """Group generated by permutations (as tuples), by closure."""
        gens = [tuple(int(x) for x in g) for g in gens]
        d = len(gens[0])
        ident = tuple(range(d))

        def comp(p, q):
            return tuple(p[q[i]] for i in range(d))

        elems, seen, frontier = [ident], {ident}, [ident]
        while frontier:
            nxt = []
            for e in frontier:
                for g in gens:
                    ne = comp(g, e)
                    if ne not in seen:
                        seen.add(ne); elems.append(ne); nxt.append(ne)
            frontier = nxt
        idx = {e: i for i, e in enumerate(elems)}
        n = len(elems)
        mult = np.array([[idx[comp(elems[a], elems[b])] for b in range(n)]
                         for a in range(n)], dtype=int)
        return cls(mult, f"<{len(gens)} perms>")
